//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumansAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Humans
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public string Image { get; set; }
    }
}
